<h1>Cadastro de produtos</h1>

<form method="POST" action="\Index\cadastrar">
    <div class="form-group">
        <label for="">Nome</label>
        <input type="text" name="nome" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Preço</label>
        <input type="number" name="preco" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Descrição</label>
        <textarea name="descricao" id="" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-default" value="Salvar">
    </div>
</form>