<h1>Entre em contato com a gente..</h1>

<form method="POST" action="<?php echo $this->url('application', ['action' => 'contato']);?>">
    <div class="form-group">
        <label for="">Nome</label>
        <input type="text" name="nome" class="form-control">
    </div>
    <div class="form-group">
        <label for="">E-mail</label>
        <input type="text" name="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Mensagem</label>
        <textarea name="" id="" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-block btn-info">
    </div>
</form>