<h1>Listagem de produtos</h1>

<table class="table table-striped">
    <thead>
        <th>Nome</th>
        <th>Preço</th>
        <th>Descrição</th>
        <th>Ações</th>
    </thead>
    <tbody>
    <?php foreach ($produtos as $produto) : ?>
        <tr>
            <td><?php echo $produto->getNome();?></td>
            <td><?php echo $produto->getPreco();?></td>
            <td><?php echo $produto->getDescricao();?></td>
            <td>
                <a href="<?php echo $this->url('application', ['action' => 'editar', 'id' => $produto->getId()]) ?>" class="btn btn-info">Editar</a>
                <a href="<?php echo $this->url('application', ['action' => 'remover', 'id' => $produto->getId()]) ?>" class="btn btn-danger">Excluir</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

