<h1>Listagem de produtos</h1>

<table class="table table-striped">
    <thead>
        <tr>Nome</tr>
        <tr>Preço</tr>
        <tr>Descrição</tr>
    </thead>
    <tbody>
    <?php foreach ($produtos as $produto) : ?>
        <tr>
            <td><?php echo $produto['nome'];?></td>
            <td><?php echo $produto['preco'];?></td>
            <td><?php echo $produto['descrica'];?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

