<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <title>Sistema de estoque</title>
        <meta charset="utf-8">
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">Estokei</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url('application',['action' => 'Index']);?>">Listagem de produtos</a></li>
                    <li><a href="<?php echo $this->url('application',['action' => 'cadastrar']);?>">Cadastro de produtos</a></li>
                </ul>
            </nav>
        </header>
        <main class="conteudo">
            <?php $this->flashHelper(); ?>
            <?php echo $this->content;?>
        </main>
        <footer class="rodape">
            Todos os direitos reservados
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
